### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by calonso**
Some improvements:

1. Improved centering
2. Fixed searching (I have some use cases with very large trees where search was not finding the intervals)
3. Added rubygems structure to be able to be pushed as a gem

Feel free to add more stuff to the gemspec file to add your details

### CODE REVIEW

**Comment by misshie** [comment]
I apologize that I did not reply sooner. Please give me several days to check your contribution.

**Comment by calonso** [comment]
That's fine, no worries. Please let me know your thoughts.

**Comment by misshie** [comment]
I AM SO SORRY. Please wait for 1 more week.... This week has a dead line for a research grant application...

**Comment by calonso** [comment]
No worries :) Good luck with your deadline!!

**Comment by calonso** [comment]
Hi @misshie, how are you doing? Any update about this?

**Comment by misshie** [comment]
Thank you very much for your patience. I have merged your contribution.I also updated README.md with your comments.

**Comment by calonso** [comment]
Perfect, now this should be ready to be deployed as a gem to rubygems server, so that people don't need to link github and we can see how many downloads etc we have. Do you want me do to push it for you? Just give link me to your Rubygems account or update the gemspec file in order for you to appear as author as well.

**Comment by misshie** [comment]
If possible, please send me an update for the gemspec file? I will register it on RubyGems.org. A gem named "interval-tree" is already used ( https://rubygems.org/gems/interval-tree ). We should use another name such as "augmented-interval-tree".

**Pull request merged**
