### PR TITLE
prepared gemspec for RubyGems upload

### PR DESCRIPTION
**Pull request by calonso**

### CODE REVIEW

**Comment by calonso** [comment]
Ok, that should do it but before publishing to RubyGems I'd like the gem tested against several Ruby versions in a CI fashion with Travis: http://docs.travis-ci.com/user/getting-started/

Can you set it up? I don't think I have permissions as the repo is yours.

**Comment by misshie** [comment]
Thank you for your pull-request. I also added the .travis.yml file. Please see the results at https://travis-ci.org/misshie/interval-tree .

**Comment by calonso** [comment]
That's great. Could you add me as a collaborator to the repo so that I can see travis builds as my own? Also let me know when you publish it in rubygems or if you want me to do it for you.

**Comment by misshie** [comment]
I added your name as a collaborator. (I did not know much about collaborator function of GitHub). I will try to publish it in RubyGems during this weekend. If I have some troubles, I will let you know. Thanks!

**Comment by misshie** [comment]
The Augmented_Interval_Tree gem is released at https://rubygems.org/gems/augmented_interval_tree .

**Comment by calonso** [comment]
@misshie That's great!!

Would you add me as a owner in rubygems as well? That way I can track downloads and stuff.
http://guides.rubygems.org/command-reference/#gem-owner this command should do it.

Thanks!

**Comment by misshie** [comment]
I added your email address as an owner of the augmented_interval_tree gem. Thank you for let me know details of the gem owner command.

Best wishes,
Hiro.

**Comment by calonso** [comment]
Thank you very much!

**Pull request merged**
